# Management Pod
apiVersion: v1
kind: Pod
metadata:
  name: cactus-client-notifications
  labels:
    app: cactus-client-notifications
spec:
  serviceAccountName: pod-creator
  containers:
    - name: environment
      image: ${CACTUS_CLIENT_NOTIFICATIONS_IMAGE}
      ports:
        - containerPort: 8080
      imagePullPolicy: Always
      env:
        - name: SERVER_URL
          value: ${CACTUS_CLIENT_NOTIFICATIONS_SERVER_URL}
        - name: MOUNT_POINT
          value: ${CACTUS_CLIENT_NOTIFICATIONS_MOUNT_POINT}

---
apiVersion: v1
kind: Service
metadata:
  name: cactus-client-notifications-service
spec:
  selector:
    app: cactus-client-notifications
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
