# Management Pod
apiVersion: v1
kind: Pod
metadata:
  name: cactus-ui
  labels:
    app: cactus-ui
spec:
  serviceAccountName: pod-creator
  containers:
    - name: environment
      image: ${CACTUS_UI_IMAGE}
      ports:
        - containerPort: 8080
      imagePullPolicy: Always
      env:
        - name : AUTH0_CLIENT_ID
          valueFrom:
              secretKeyRef:
                name: cactus-ui-oauth2-client-id
                key: OAUTH2_CLIENT_ID
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
              secretKeyRef:
                name: cactus-ui-oauth2-client-secret
                key: OAUTH2_CLIENT_SECRET
        - name: AUTH0_DOMAIN
          valueFrom:
              secretKeyRef:
                name: cactus-ui-oauth2-domain
                key: OAUTH2_DOMAIN
        - name: APP_SECRET_KEY
          valueFrom:
              secretKeyRef:
                name: cactus-ui-app-key
                key: APP_SECRET_KEY
        - name: CACTUS_ORCHESTRATOR_BASEURL
          value: ${CACTUS_ORCHESTRATOR_BASEURL}
        - name: CACTUS_ORCHESTRATOR_AUDIENCE
          value: ${CACTUS_ORCHESTRATOR_AUDIENCE}
        - name: CACTUS_PLATFORM_VERSION
          value: ${CACTUS_PLATFORM_VERSION}
        - name: CACTUS_PLATFORM_SUPPORT_EMAIL
          value: ${CACTUS_PLATFORM_SUPPORT_EMAIL}
        - name: CACTUS_ORCHESTRATOR_REQUEST_TIMEOUT_DEFAULT
          value: "180"
        - name: CACTUS_ORCHESTRATOR_REQUEST_TIMEOUT_SPAWN
          value: "300"
---
apiVersion: v1
kind: Service
metadata:
  name: cactus-ui-service
spec:
  selector:
    app: cactus-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
