apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cactus-teststack-imagepuller
  namespace: teststack-templates
spec:
  selector:
    matchLabels:
      name: cactus-teststack-imagepuller
  template:
    metadata:
      labels:
        name: cactus-teststack-imagepuller
    spec:
      initContainers:
        # These init containers will force k8's to pull all the specified images across all nodes
        - name: common-orchestrator
          image: ${CACTUS_ORCHESTRATOR_IMAGE}
          command: ["sh", "-c", "'true'"]
        - name: common-ui
          image: ${CACTUS_UI_IMAGE}
          command: ["sh", "-c", "'true'"]
        - name: v12-runner
          image: ${CACTUS_RUNNER_IMAGE_V12}
          command: ["sh", "-c", "'true'"]
        - name: v12-db
          image: ${CACTUS_ENVOY_DB_IMAGE_V12}
          command: ["sh", "-c", "'true'"]
        - name: v12-init
          image: ${CACTUS_TESTSTACK_INIT_IMAGE_V12}
          command: ["sh", "-c", "'true'"]
        - name: v12-envoy
          image: ${CACTUS_ENVOY_APP_IMAGE_V12}
          command: ["sh", "-c", "'true'"]
        - name: v13-beta-storage-runner
          image: ${CACTUS_RUNNER_IMAGE_V13_BETA_STORAGE}
          command: ["sh", "-c", "'true'"]
        - name: v13-beta-storage-db
          image: ${CACTUS_ENVOY_DB_IMAGE_V13_BETA_STORAGE}
          command: ["sh", "-c", "'true'"]
        - name: v13-beta-storage-init
          image: ${CACTUS_TESTSTACK_INIT_IMAGE_V13_BETA_STORAGE}
          command: ["sh", "-c", "'true'"]
        - name: v13-beta-storage-envoy
          image: ${CACTUS_ENVOY_APP_IMAGE_V13_BETA_STORAGE}
          command: ["sh", "-c", "'true'"]

        
      containers:
        # This will sit idle, doing nothing (thus ensuring k8s will pull all the init containers)
        - name: pause
          image: rancher/pause:3.6